services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: market
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: postgres
    ports:
      - 127.0.0.1:5432:5432